[workspace]
resolver = "3"
members = ["api", "core"]

[workspace.package]
name = "plannify-driver-api"
edition = "2024"
version = "0.1.0"
authors = ["Plannify <contact@plannify.be>"]
license = "Apache-2.0"

[workspace.dependencies]
thiserror = "2.0.17"