name: SECRET

on:
  push:
    branches:
      - "*"

jobs:
  secret-detection:
    name: Secret Analysis
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gitleaks/gitleaks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Secret Analysis
        run: gitleaks dir --no-banner --verbose --redact=100 --report-format=json --report-path report.json --log-level=info --exit-code=0 .

      - name: Upload Secret Report
        uses: actions/upload-artifact@v3
        with:
          name: secret-report
          path: report.json
