name: security

on:
  push:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-detection:
    name: Rust Linting and Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Lint
        run: cargo clippy --verbose

  sast-detection:
    name: SAST Analysis
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SAST Analysis
        run: semgrep ci --config=auto --code --no-suppress-errors --json

  secret-detection:
    name: Secret Analysis
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gitleaks/gitleaks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Secret Analysis
        run: gitleaks dir --no-banner --verbose --redact=100 --report-format=json --report-path report.json --log-level=info --exit-code=0 .

      - name: Upload Secret Report
        uses: actions/upload-artifact@v6
        with:
          name: secret-report
          path: report.json

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - lint-detection
      - sast-detection
      - secret-detection
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Test
        run: cargo test --verbose
